import { calculateClamp, calculateTypeScale, calculateSpaceScale } from 'utopia-core'
import type { ResponsiveConfig, GeneratedToken, GeneratorResult } from '../types'
import { validate } from './validate'

const HEADER = `/* tokens.responsive.css
 *
 * AUTO-GENERATED by tools/responsive-tokens-editor/ — do not edit manually.
 * Source of truth: packages/ui/src/theme/responsive-config.json
 *
 * Cascade-overrides static tokens defined in tokens.css with clamp()-based
 * fluid values. RTL-safe via 'vi' (viewport-inline) units.
 *
 * See ADR-025 (Responsive Blocks) and WP-030 (Responsive Tokens Editor).
 */`

/**
 * Container BP thresholds — Phase 5 (WP-030) hardcoded constants.
 *
 * Mobile applies below TABLET_BP; tablet @media applies from TABLET_BP up to
 * DESKTOP_BP-1; desktop @media applies from DESKTOP_BP up. Making these
 * editable in the schema is a V2 concern — V1 keeps the schema minimal by
 * fixing the BPs and exposing only the per-BP values in the editor.
 */
const TABLET_BP = 768
const DESKTOP_BP = 1280

/**
 * Convert config → tokens.responsive.css string + per-token diagnostics.
 *
 * Discipline:
 *   - Every entry in config.overrides → emit explicit clamp() with override min/max
 *   - For tokens NOT in overrides but present in stepMap → derive from utopia-core
 *     calculateTypeScale (V1 produces nothing here; future-token coverage)
 *   - Spacing tokens NOT in overrides but in multipliers → derive from
 *     calculateSpaceScale customSizes (V1: same — overrides cover all)
 *   - All clamp() output uses 'vi' units via relativeTo: 'viewport' (PF.2 / WP §Output format)
 */
export function generateTokensCss(config: ResponsiveConfig): GeneratorResult {
  const tokens: GeneratedToken[] = []

  // 1. Override-driven tokens (V1: covers all 22 active tokens)
  for (const [name, override] of Object.entries(config.overrides)) {
    const clampCss = calculateClamp({
      minSize: override.minPx,
      maxSize: override.maxPx,
      minWidth: config.minViewport,
      maxWidth: config.maxViewport,
      relativeTo: 'viewport', // PF.2 — emits 'vi' (RTL-safe)
    })
    tokens.push({
      name,
      minPx: override.minPx,
      maxPx: override.maxPx,
      clampCss,
      source: name === '--space-section' ? 'special' : 'override',
    })
  }

  // 2. (Future) Type-scale-derived tokens — entries in stepMap NOT in overrides.
  //    V1: empty (every stepMap token has an explicit override).
  const typeScale = calculateTypeScale({
    minWidth: config.minViewport,
    maxWidth: config.maxViewport,
    minFontSize: config.type.baseAtMin,
    maxFontSize: config.type.baseAtMax,
    minTypeScale: config.type.ratioAtMin,
    maxTypeScale: config.type.ratioAtMax,
    positiveSteps: 6,
    negativeSteps: 3,
  })
  for (const [stepStr, entry] of Object.entries(config.type.stepMap)) {
    if (config.overrides[entry.token] !== undefined) continue
    const step = Number(stepStr)
    const stepData = typeScale.find((s) => s.step === step)
    if (!stepData) continue
    const clampCss = calculateClamp({
      minSize: stepData.minFontSize,
      maxSize: stepData.maxFontSize,
      minWidth: config.minViewport,
      maxWidth: config.maxViewport,
      relativeTo: 'viewport',
    })
    tokens.push({
      name: entry.overrides,
      minPx: stepData.minFontSize,
      maxPx: stepData.maxFontSize,
      clampCss,
      source: 'type-scale',
    })
  }

  // 3. (Future) Space-scale-derived tokens — multipliers entries NOT in overrides.
  //    V1: empty (every spacing token has an explicit override).
  const spaceScale = calculateSpaceScale({
    minWidth: config.minViewport,
    maxWidth: config.maxViewport,
    minSize: config.spacing.baseAtMin,
    maxSize: config.spacing.baseAtMax,
    positiveSteps: [1.5, 2, 2.5, 3, 4],
    negativeSteps: [0.75, 0.5, 0.25, 0.125],
  })
  // (Phase 2 V1: spaceScale is computed but not used — every multiplier is overridden.
  // Phase 3+ override-removal flow uses these as fallback values.)
  void spaceScale

  // 4. Validate via utopia-core checkWCAG (per Ruling #3)
  const wcagViolations = validate(config, tokens)
  for (const violation of wcagViolations) {
    const t = tokens.find((tok) => tok.name === violation.token)
    if (t) t.wcagViolation = violation
  }

  // 5. Emit CSS string
  const lines = [HEADER, '', ':root {']
  // Group: typography first, spacing second, special last (matches existing tokens.css order)
  const groups = [
    { label: '/* Typography — fluid clamps */', filter: (t: GeneratedToken) => t.name.includes('font-size') || t.name === '--text-display' },
    { label: '/* Spacing — fluid clamps */',    filter: (t: GeneratedToken) => t.name.startsWith('--spacing-') },
    { label: '/* Section rhythm */',             filter: (t: GeneratedToken) => t.name === '--space-section' },
  ]
  for (const group of groups) {
    const groupTokens = tokens.filter(group.filter)
    if (groupTokens.length === 0) continue
    lines.push('  ' + group.label)
    for (const t of groupTokens) {
      lines.push(`  ${t.name}: ${t.clampCss};`)
    }
    lines.push('')
  }
  // Trim trailing blank line + close the :root token-clamp block
  while (lines[lines.length - 1] === '') lines.pop()
  lines.push('}')
  lines.push('')

  // 6. Container BP overrides — discrete per-BP values (Phase 5 WP-030).
  //    NOT fluid clamp: per WP §Container widths sub-editor design rationale.
  //    Mobile :root applies below TABLET_BP; @media tablet/desktop cascade.
  const { mobile, tablet, desktop } = config.containers
  const mobileMaxW =
    typeof mobile.maxWidth === 'number' ? `${mobile.maxWidth}px` : mobile.maxWidth

  lines.push('/* Container widths — discrete per-BP (NOT fluid clamp) */')
  lines.push(':root {')
  lines.push(`  --container-max-w: ${mobileMaxW};`)
  lines.push(`  --container-px: ${mobile.px}px;`)
  lines.push('}')
  lines.push('')

  lines.push(`@media (min-width: ${TABLET_BP}px) {`)
  lines.push('  :root {')
  lines.push(`    --container-max-w: ${tablet.maxWidth}px;`)
  lines.push(`    --container-px: ${tablet.px}px;`)
  lines.push('  }')
  lines.push('}')
  lines.push('')

  lines.push(`@media (min-width: ${DESKTOP_BP}px) {`)
  lines.push('  :root {')
  lines.push(`    --container-max-w: ${desktop.maxWidth}px;`)
  lines.push(`    --container-px: ${desktop.px}px;`)
  lines.push('  }')
  lines.push('}')
  lines.push('')

  return {
    css: lines.join('\n'),
    tokens,
    wcagViolations,
  }
}
