/**
 * Domain Manifest — Source of Truth for the CMSMasters Portal monorepo.
 *
 * This is a DECLARATIVE CONTRACT. It defines ownership boundaries.
 * Code must conform to the manifest, not the other way around.
 *
 * When adding/moving/deleting files: update this manifest.
 * Run `npm run arch-test` to verify.
 */

// ── Interface ──

export interface DomainDefinition {
  name: string
  slug: string
  description: string

  /** Monorepo-relative paths to all source files owned by this domain */
  owned_files: string[]

  /** Supabase tables this domain is authoritative for */
  owned_tables: string[]

  /** Hono API route files owned by this domain */
  owned_routes: string[]

  /** Files other domains may import from this one */
  public_entrypoints: string[]

  /** Domain slugs this domain is allowed to import from */
  allowed_imports_from: string[]

  /** Severity-tagged gaps: 'critical: ...' | 'important: ...' | 'note: ...' */
  known_gaps: string[]

  /** Optional policy: 'isolated' (own theme, no Portal DS), 'meta' (non-code) */
  policy?: string
}

// ── Domains ──

export const DOMAINS: Record<string, DomainDefinition> = {

  // ────────────────────────────────────────
  // PACKAGE DOMAINS
  // ────────────────────────────────────────

  'pkg-db': {
    name: 'Database Package',
    slug: 'pkg-db',
    description: 'Supabase client, typed queries, mappers for all 9 tables.',
    owned_files: [
      'packages/db/src/index.ts',
      'packages/db/src/client.ts',
      'packages/db/src/types.ts',
      'packages/db/src/mappers.ts',
      'packages/db/src/queries/audit.ts',
      'packages/db/src/queries/blocks.ts',
      'packages/db/src/queries/global-elements.ts',
      'packages/db/src/queries/pages.ts',
      'packages/db/src/queries/profiles.ts',
      'packages/db/src/queries/templates.ts',
      'packages/db/src/queries/themes.ts',
      'packages/db/src/__tests__/mappers.test.ts',
      'packages/db/src/__tests__/phase2-smoke.test.ts',
    ],
    owned_tables: [
      'profiles',
      'themes',
      'blocks',
      'templates',
      'pages',
      'page_blocks',
      'global_elements',
      'licenses',
      'audit_log',
    ],
    owned_routes: [],
    public_entrypoints: ['packages/db/src/index.ts'],
    allowed_imports_from: [],
    known_gaps: [
      'note: types.ts is generated from Supabase — manual edits will be overwritten',
      'important: mappers.ts handles snake_case→camelCase but has no runtime validation',
      'note: licenses table declared but no queries file yet — Dashboard will add it',
    ],
  },

  'pkg-auth': {
    name: 'Auth Package',
    slug: 'pkg-auth',
    description: 'Supabase PKCE auth: client, hooks, guards, magic link actions.',
    owned_files: [
      'packages/auth/src/index.ts',
      'packages/auth/src/client.ts',
      'packages/auth/src/hooks.ts',
      'packages/auth/src/guards.tsx',
      'packages/auth/src/actions.ts',
      'packages/auth/src/types.ts',
      'packages/auth/src/env.d.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/auth/src/index.ts'],
    allowed_imports_from: ['pkg-db'],
    known_gaps: [
      'note: guards.tsx depends on useRole from hooks.ts — role comes from profiles table via pkg-db',
    ],
  },

  'pkg-ui': {
    name: 'UI Package',
    slug: 'pkg-ui',
    description: 'Design system: tokens, primitives, portal block styles, animation utilities.',
    owned_files: [
      'packages/ui/src/lib/utils.ts',
      'packages/ui/src/primitives/button.tsx',
      'packages/ui/src/primitives/button.stories.tsx',
      'packages/ui/src/portal/animate-utils.js',
      'packages/ui/src/portal/portal-blocks.css',
      'packages/ui/src/theme/tokens.css',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/ui/src/lib/utils.ts', 'packages/ui/src/primitives/button.tsx'],
    allowed_imports_from: [],
    known_gaps: [
      'note: tokens.css is auto-generated by /sync-tokens — do not edit manually',
      'important: portal-blocks.css provides .cms-btn system used by all portal blocks',
    ],
  },

  'pkg-validators': {
    name: 'Validators Package',
    slug: 'pkg-validators',
    description: 'Zod schemas for theme, block, template, page validation.',
    owned_files: [
      'packages/validators/src/index.ts',
      'packages/validators/src/block.ts',
      'packages/validators/src/page.ts',
      'packages/validators/src/template.ts',
      'packages/validators/src/theme.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/validators/src/index.ts'],
    allowed_imports_from: [],
    known_gaps: [],
  },

  'pkg-api-client': {
    name: 'API Client Package',
    slug: 'pkg-api-client',
    description: 'Hono RPC typed client for calling the API from SPAs.',
    owned_files: [
      'packages/api-client/src/client.ts',
      'packages/api-client/src/index.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/api-client/src/index.ts'],
    allowed_imports_from: [],
    known_gaps: [],
  },

  // ────────────────────────────────────────
  // APP DOMAINS
  // ────────────────────────────────────────

  'app-portal': {
    name: 'Portal App',
    slug: 'app-portal',
    description: 'Next.js 15 SSG+ISR public site: theme pages, composed pages, SEO, revalidation.',
    owned_files: [
      'apps/portal/app/layout.tsx',
      'apps/portal/app/globals.css',
      'apps/portal/app/sitemap.ts',
      'apps/portal/app/[[...slug]]/page.tsx',
      'apps/portal/app/themes/[slug]/page.tsx',
      'apps/portal/app/_components/block-renderer.tsx',
      'apps/portal/app/api/revalidate/route.ts',
      'apps/portal/lib/blocks.ts',
      'apps/portal/lib/global-elements.ts',
      'apps/portal/lib/hooks.ts',
      'apps/portal/lib/supabase.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-ui'],
    known_gaps: [
      'note: [[...slug]] catch-all handles composed pages — new pages need revalidation',
      'important: hook resolution ({{price}} → theme.meta.price) is build-time string replacement in RSC',
    ],
  },

  'studio-blocks': {
    name: 'Studio Block Pipeline',
    slug: 'studio-blocks',
    description: 'Block editor, import panel, CSS token scanner, token map — the processing pipeline.',
    owned_files: [
      'apps/studio/src/pages/block-editor.tsx',
      'apps/studio/src/components/block-import-panel.tsx',
      'apps/studio/src/lib/block-processor.ts',
      'apps/studio/src/lib/token-map.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-validators', 'pkg-api-client', 'pkg-ui', 'studio-core'],
    known_gaps: [
      'important: block-processor depends on token-map — if tokens.css changes, token-map may need updates',
      'note: processing is 100% client-side — no API calls for token analysis',
    ],
  },

  'studio-core': {
    name: 'Studio App Shell & CRUD',
    slug: 'studio-core',
    description: 'Vite SPA shell, routing, layouts, auth pages, and entity CRUD for themes/blocks/templates/pages/global-elements.',
    owned_files: [
      // entry + app
      'apps/studio/src/main.tsx',
      'apps/studio/src/app.tsx',
      'apps/studio/src/globals.css',
      // layouts
      'apps/studio/src/layouts/app-layout.tsx',
      'apps/studio/src/layouts/auth-layout.tsx',
      // pages (12, excl block-editor which is in studio-blocks)
      'apps/studio/src/pages/blocks-list.tsx',
      'apps/studio/src/pages/elements-list.tsx',
      'apps/studio/src/pages/global-elements-settings.tsx',
      'apps/studio/src/pages/login.tsx',
      'apps/studio/src/pages/media.tsx',
      'apps/studio/src/pages/not-found.tsx',
      'apps/studio/src/pages/page-editor.tsx',
      'apps/studio/src/pages/pages-list.tsx',
      'apps/studio/src/pages/template-editor.tsx',
      'apps/studio/src/pages/templates-list.tsx',
      'apps/studio/src/pages/theme-editor.tsx',
      'apps/studio/src/pages/themes-list.tsx',
      // components (19, excl block-import-panel which is in studio-blocks)
      'apps/studio/src/components/block-picker-modal.tsx',
      'apps/studio/src/components/block-preview.tsx',
      'apps/studio/src/components/char-counter.tsx',
      'apps/studio/src/components/chip-select.tsx',
      'apps/studio/src/components/delete-confirm-modal.tsx',
      'apps/studio/src/components/editor-footer.tsx',
      'apps/studio/src/components/editor-sidebar.tsx',
      'apps/studio/src/components/error-boundary.tsx',
      'apps/studio/src/components/form-section.tsx',
      'apps/studio/src/components/pagination.tsx',
      'apps/studio/src/components/position-grid.tsx',
      'apps/studio/src/components/sidebar.tsx',
      'apps/studio/src/components/star-rating.tsx',
      'apps/studio/src/components/status-badge.tsx',
      'apps/studio/src/components/template-picker.tsx',
      'apps/studio/src/components/theme-card.tsx',
      'apps/studio/src/components/themes-table.tsx',
      'apps/studio/src/components/themes-toolbar.tsx',
      'apps/studio/src/components/toast.tsx',
      'apps/studio/src/components/topbar.tsx',
      // lib (9, excl block-processor + token-map which are in studio-blocks)
      'apps/studio/src/lib/api.ts',
      'apps/studio/src/lib/block-api.ts',
      'apps/studio/src/lib/form-defaults.ts',
      'apps/studio/src/lib/format.ts',
      'apps/studio/src/lib/global-element-api.ts',
      'apps/studio/src/lib/page-api.ts',
      'apps/studio/src/lib/queries.ts',
      'apps/studio/src/lib/supabase.ts',
      'apps/studio/src/lib/template-api.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-auth', 'pkg-validators', 'pkg-api-client', 'pkg-ui'],
    known_gaps: [
      'important: block-api.ts exports shared authHeaders/parseError used by ALL entity API wrappers',
      'note: elements-list.tsx is blocks filtered by category === "element" — not a separate entity',
      'note: all editors duplicate inputStyle/labelStyle inline objects — no shared style component',
    ],
  },

  'app-api': {
    name: 'Hono API',
    slug: 'app-api',
    description: 'Hono on Cloudflare Workers: CRUD routes, auth middleware, R2 upload, revalidation. Only place secrets live.',
    owned_files: [
      'apps/api/src/index.ts',
      'apps/api/src/env.ts',
      'apps/api/src/lib/supabase.ts',
      'apps/api/src/middleware/auth.ts',
      'apps/api/src/middleware/role.ts',
      'apps/api/src/routes/blocks.ts',
      'apps/api/src/routes/global-elements.ts',
      'apps/api/src/routes/health.ts',
      'apps/api/src/routes/pages.ts',
      'apps/api/src/routes/revalidate.ts',
      'apps/api/src/routes/templates.ts',
      'apps/api/src/routes/upload.ts',
    ],
    owned_tables: [],
    owned_routes: [
      'apps/api/src/routes/blocks.ts',
      'apps/api/src/routes/global-elements.ts',
      'apps/api/src/routes/health.ts',
      'apps/api/src/routes/pages.ts',
      'apps/api/src/routes/revalidate.ts',
      'apps/api/src/routes/templates.ts',
      'apps/api/src/routes/upload.ts',
    ],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-validators'],
    known_gaps: [
      'important: secrets boundary — Envato key, Resend key, Claude API key, R2 creds, service_role ONLY here',
      'note: supabase client uses service_role key — bypasses RLS',
    ],
  },

  'app-command-center': {
    name: 'Command Center App',
    slug: 'app-command-center',
    description: 'Internal project management tool. Own dark theme, fully isolated from Portal DS.',
    owned_files: [
      // app routes
      'apps/command-center/app/layout.tsx',
      'apps/command-center/app/page.tsx',
      'apps/command-center/app/globals.css',
      'apps/command-center/app/architecture/page.tsx',
      'apps/command-center/app/architecture/[id]/page.tsx',
      'apps/command-center/app/architecture/ArchitectureTabs.tsx',
      'apps/command-center/app/components/page.tsx',
      'apps/command-center/app/components/[id]/page.tsx',
      'apps/command-center/app/components/[id]/component-preview.tsx',
      'apps/command-center/app/content/page.tsx',
      'apps/command-center/app/dependencies/page.tsx',
      'apps/command-center/app/phases/page.tsx',
      'apps/command-center/app/phases/[id]/page.tsx',
      // components
      'apps/command-center/components/ADRViewer.tsx',
      'apps/command-center/components/ActivityFeed.tsx',
      'apps/command-center/components/AgentationToolbar.tsx',
      'apps/command-center/components/AppCard.tsx',
      'apps/command-center/components/BurndownChart.tsx',
      'apps/command-center/components/ComponentCard.tsx',
      'apps/command-center/components/ContentOverview.tsx',
      'apps/command-center/components/DependencyGraph.tsx',
      'apps/command-center/components/DesignSystemProgress.tsx',
      'apps/command-center/components/GlobalSearch.tsx',
      'apps/command-center/components/InfraChecklist.tsx',
      'apps/command-center/components/PhaseCard.tsx',
      'apps/command-center/components/PhaseTimeline.tsx',
      'apps/command-center/components/PhaseTrackerClient.tsx',
      'apps/command-center/components/Sidebar.tsx',
      'apps/command-center/components/TaskBrowser.tsx',
      'apps/command-center/components/TaskDetailSheet.tsx',
      'apps/command-center/components/TaskFilters.tsx',
      'apps/command-center/components/TaskTable.tsx',
      'apps/command-center/components/TasksView.tsx',
      'apps/command-center/components/ThemeStatusTable.tsx',
      // ui
      'apps/command-center/ui/AtomsShowcase.tsx',
      'apps/command-center/ui/Card.tsx',
      'apps/command-center/ui/Checkbox.tsx',
      'apps/command-center/ui/DonutChart.tsx',
      'apps/command-center/ui/Input.tsx',
      'apps/command-center/ui/Modal.tsx',
      'apps/command-center/ui/ProgressBar.tsx',
      'apps/command-center/ui/Select.tsx',
      'apps/command-center/ui/StatusBadge.tsx',
      'apps/command-center/ui/StatusDots.tsx',
      'apps/command-center/ui/TokenCoveragePanel.tsx',
      // lib
      'apps/command-center/lib/data.ts',
      'apps/command-center/lib/phase-sync.ts',
      'apps/command-center/lib/scanner.ts',
      'apps/command-center/lib/types.ts',
      'apps/command-center/lib/utils.ts',
      // cli
      'apps/command-center/cli/report.ts',
      'apps/command-center/cli/scan.ts',
      // theme
      'apps/command-center/theme/tokens.ts',
      'apps/command-center/theme/utils.ts',
      // types
      'apps/command-center/types/tailwindcss.d.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: [],
    known_gaps: [
      'note: has own dark zinc theme — do NOT apply Portal DS tokens',
      'note: ui/ directory is CC-local components — not @cmsmasters/ui',
    ],
    policy: 'isolated',
  },

  'infra-tooling': {
    name: 'Infrastructure & Tooling',
    slug: 'infra-tooling',
    description: 'Monorepo config, context docs, workplans, dev tools. Non-code meta domain.',
    owned_files: [
      '.context/BRIEF.md',
      '.context/ADR_DIGEST.md',
      '.context/CONVENTIONS.md',
      '.context/LAYER_0_SPEC.md',
      '.context/ROADMAP.md',
      '.context/SKILL.md',
      '.context/DESKTOP_SKILL.md',
      '.context/FIGMA_DESIGN_WORKFLOW.md',
      'tools/test-scanner.ts',
      'tools/sync-tokens/README.md',
      'tools/sync-tokens/figma.config.json',
      'nx.json',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: [],
    known_gaps: [
      'note: workplan/*.md and tools/studio-mockups/*.html tracked as directory — not individual files',
    ],
    policy: 'meta',
  },
}

// ── Shared Infrastructure ──

/** Files used by multiple domains but not exclusively owned by any single domain */
export const SHARED_INFRASTRUCTURE = {
  root_configs: [
    'package.json',
    'tsconfig.json',
    'eslint.config.mjs',
    'knip.json',
  ],
}
