/**
 * Domain Manifest — Source of Truth for the CMSMasters Portal monorepo.
 *
 * This is a DECLARATIVE CONTRACT. It defines ownership boundaries.
 * Code must conform to the manifest, not the other way around.
 *
 * When adding/moving/deleting files: update this manifest.
 * Run `npm run arch-test` to verify.
 */

// ── Interface ──

export interface DomainDefinition {
  name: string
  slug: string
  description: string

  /** Monorepo-relative paths to all source files owned by this domain */
  owned_files: string[]

  /** Supabase tables this domain is authoritative for */
  owned_tables: string[]

  /** Hono API route files owned by this domain */
  owned_routes: string[]

  /** Files other domains may import from this one */
  public_entrypoints: string[]

  /** Domain slugs this domain is allowed to import from */
  allowed_imports_from: string[]

  /** Severity-tagged gaps: 'critical: ...' | 'important: ...' | 'note: ...' */
  known_gaps: string[]

  /** Optional policy: 'isolated' (own theme, no Portal DS), 'meta' (non-code) */
  policy?: string
}

// ── Domains ──

export const DOMAINS: Record<string, DomainDefinition> = {

  // ────────────────────────────────────────
  // PACKAGE DOMAINS
  // ────────────────────────────────────────

  'pkg-db': {
    name: 'Database Package',
    slug: 'pkg-db',
    description: 'Supabase client, typed queries, mappers for all 13 tables.',
    owned_files: [
      'packages/db/src/index.ts',
      'packages/db/src/client.ts',
      'packages/db/src/types.ts',
      'packages/db/src/slot-registry.ts',
      'packages/db/src/mappers.ts',
      'packages/db/src/queries/audit.ts',
      'packages/db/src/queries/blocks.ts',
      'packages/db/src/queries/global-elements.ts',
      'packages/db/src/queries/pages.ts',
      'packages/db/src/queries/profiles.ts',
      'packages/db/src/queries/templates.ts',
      'packages/db/src/queries/themes.ts',
      'packages/db/src/queries/categories.ts',
      'packages/db/src/queries/tags.ts',
      'packages/db/src/queries/prices.ts',
      'packages/db/src/queries/block-categories.ts',
      'packages/db/src/queries/use-cases.ts',
      'packages/db/src/queries/staff-roles.ts',
      'packages/db/src/queries/activity.ts',
      'packages/db/src/queries/licenses.ts',
      'packages/db/src/queries/envato.ts',
      'packages/db/src/__tests__/mappers.test.ts',
      'packages/db/src/__tests__/phase2-smoke.test.ts',
    ],
    owned_tables: [
      'profiles',
      'themes',
      'blocks',
      'templates',
      'pages',
      'page_blocks',
      'global_elements',
      'licenses',
      'audit_log',
      'staff_roles',
      'activity_log',
      'categories',
      'tags',
      'theme_categories',
      'theme_tags',
      'prices',
      'theme_prices',
      'block_categories',
      'use_cases',
      'theme_use_cases',
    ],
    owned_routes: [],
    public_entrypoints: ['packages/db/src/index.ts'],
    allowed_imports_from: [],
    known_gaps: [
      'note: types.ts is generated from Supabase — manual edits will be overwritten',
      'important: mappers.ts handles snake_case→camelCase but has no runtime validation',
      'note: licenses queries added in WP-017 phase 1',
    ],
  },

  'pkg-auth': {
    name: 'Auth Package',
    slug: 'pkg-auth',
    description: 'Supabase PKCE auth: client, hooks, guards, magic link actions.',
    owned_files: [
      'packages/auth/src/index.ts',
      'packages/auth/src/client.ts',
      'packages/auth/src/hooks.ts',
      'packages/auth/src/guards.tsx',
      'packages/auth/src/actions.ts',
      'packages/auth/src/types.ts',
      'packages/auth/src/resolvers.ts',
      'packages/auth/src/env.d.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/auth/src/index.ts'],
    allowed_imports_from: ['pkg-db'],
    known_gaps: [
      'note: guards.tsx depends on useRole from hooks.ts — role comes from profiles table via pkg-db',
    ],
  },

  'pkg-ui': {
    name: 'UI Package',
    slug: 'pkg-ui',
    description: 'Design system: tokens, primitives, portal block styles, animation utilities.',
    owned_files: [
      'packages/ui/src/lib/utils.ts',
      'packages/ui/src/primitives/button.tsx',
      'packages/ui/src/primitives/drawer.tsx',
      'packages/ui/src/primitives/slider.tsx',
      'packages/ui/src/portal/animate-utils.js',
      'packages/ui/src/portal/portal-blocks.css',
      'packages/ui/src/theme/tokens.css',
      'packages/ui/src/theme/tokens.responsive.css',
      'packages/ui/src/theme/tokens.responsive.opt-out.css',
      'packages/ui/src/theme/responsive-config.json',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/ui/src/lib/utils.ts', 'packages/ui/src/primitives/button.tsx'],
    allowed_imports_from: [],
    known_gaps: [
      'note: tokens.css is auto-generated by /sync-tokens — do not edit manually',
      'important: portal-blocks.css provides .cms-btn system used by all portal blocks',
      'note: tokens.responsive.css is machine-generated by tools/responsive-tokens-editor (WP-030 P6) — SOT is responsive-config.json',
      'note: responsive-config.json is the SOT for the fluid scale; edits go through tools/responsive-tokens-editor :7703 Save flow',
      'note: tokens.responsive.opt-out.css is HAND-MAINTAINED mirror of tokens.responsive.css maxPx values (post-WP-030 redesign); provides [data-fluid-tablet="off"] (768-1279px @media) and [data-fluid-mobile="off"] (<768px @media) per-BP hooks. Legacy [data-fluid="off"|"desktop-only"] is parse-only in tools/block-forge/src/lib/fluid-mode.ts — no longer emitted. Drift caveat: editor regeneration of this file is polish-queue work tracked for WP-031.',
    ],
  },

  'pkg-validators': {
    name: 'Validators Package',
    slug: 'pkg-validators',
    description: 'Zod schemas for theme, block, template, page validation.',
    owned_files: [
      'packages/validators/src/index.ts',
      'packages/validators/src/block.ts',
      'packages/validators/src/page.ts',
      'packages/validators/src/template.ts',
      'packages/validators/src/theme.ts',
      'packages/validators/src/category.ts',
      'packages/validators/src/tag.ts',
      'packages/validators/src/block-category.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/validators/src/index.ts'],
    allowed_imports_from: [],
    known_gaps: [],
  },

  'pkg-api-client': {
    name: 'API Client Package',
    slug: 'pkg-api-client',
    description: 'Hono RPC typed client for calling the API from SPAs.',
    owned_files: [
      'packages/api-client/src/client.ts',
      'packages/api-client/src/index.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/api-client/src/index.ts'],
    allowed_imports_from: [],
    known_gaps: [],
  },

  'pkg-block-forge-core': {
    name: 'Block Forge Core Engine',
    slug: 'pkg-block-forge-core',
    description: 'Framework-agnostic responsive block authoring — CSS analyzer, auto-rules, tweak emitter, variant composer, preview renderer. Pure functions.',
    owned_files: [
      'packages/block-forge-core/package.json',
      'packages/block-forge-core/README.md',
      'packages/block-forge-core/tsconfig.json',
      'packages/block-forge-core/vitest.config.ts',
      'packages/block-forge-core/src/index.ts',
      'packages/block-forge-core/src/lib/types.ts',
      'packages/block-forge-core/src/__tests__/smoke.test.ts',
      'packages/block-forge-core/src/analyze/parse-css.ts',
      'packages/block-forge-core/src/analyze/parse-html.ts',
      'packages/block-forge-core/src/analyze/analyze-block.ts',
      'packages/block-forge-core/src/__tests__/analyze-block.test.ts',
      'packages/block-forge-core/src/lib/hash.ts',
      'packages/block-forge-core/src/rules/index.ts',
      'packages/block-forge-core/src/rules/heuristic-grid-cols.ts',
      'packages/block-forge-core/src/rules/heuristic-spacing-clamp.ts',
      'packages/block-forge-core/src/rules/heuristic-font-clamp.ts',
      'packages/block-forge-core/src/rules/heuristic-flex-wrap.ts',
      'packages/block-forge-core/src/rules/heuristic-horizontal-overflow.ts',
      'packages/block-forge-core/src/rules/heuristic-media-maxwidth.ts',
      'packages/block-forge-core/src/__tests__/heuristic-grid-cols.test.ts',
      'packages/block-forge-core/src/__tests__/heuristic-spacing-clamp.test.ts',
      'packages/block-forge-core/src/__tests__/heuristic-font-clamp.test.ts',
      'packages/block-forge-core/src/__tests__/heuristic-flex-wrap.test.ts',
      'packages/block-forge-core/src/__tests__/heuristic-horizontal-overflow.test.ts',
      'packages/block-forge-core/src/__tests__/heuristic-media-maxwidth.test.ts',
      'packages/block-forge-core/src/__tests__/rules-dispatcher.test.ts',
      'packages/block-forge-core/src/compose/apply-suggestions.ts',
      'packages/block-forge-core/src/compose/emit-tweak.ts',
      'packages/block-forge-core/src/compose/compose-variants.ts',
      'packages/block-forge-core/src/compose/render-preview.ts',
      'packages/block-forge-core/src/lib/container-query.ts',
      'packages/block-forge-core/src/lib/css-scoping.ts',
      'packages/block-forge-core/src/__tests__/apply-suggestions.test.ts',
      'packages/block-forge-core/src/__tests__/emit-tweak.test.ts',
      'packages/block-forge-core/src/__tests__/compose-variants.test.ts',
      'packages/block-forge-core/src/__tests__/render-preview.test.ts',
      'packages/block-forge-core/src/__tests__/snapshot.test.ts',
      'packages/block-forge-core/src/__tests__/README.md',
      'packages/block-forge-core/src/__tests__/fixtures/README.md',
      'packages/block-forge-core/src/__tests__/fixtures/block-spacing-font.html',
      'packages/block-forge-core/src/__tests__/fixtures/block-spacing-font.css',
      'packages/block-forge-core/src/__tests__/fixtures/block-plain-copy.html',
      'packages/block-forge-core/src/__tests__/fixtures/block-plain-copy.css',
      'packages/block-forge-core/src/__tests__/fixtures/block-nested-row.html',
      'packages/block-forge-core/src/__tests__/fixtures/block-nested-row.css',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: ['packages/block-forge-core/src/index.ts'],
    allowed_imports_from: ['pkg-db'],
    known_gaps: [
      'important: heuristics never auto-apply — consumers MUST present suggestions for accept/tweak/reject per ADR-025',
      'important: heuristics skip values containing var()/calc()/clamp()/min()/max()/%/vw/vh/em (rem allowed) — tokenized content does NOT trigger clamp suggestions by design',
      'note: fixture blocks in src/__tests__/fixtures/ are frozen; never /content-pull into this folder',
    ],
  },

  // ────────────────────────────────────────
  // APP DOMAINS
  // ────────────────────────────────────────

  'app-portal': {
    name: 'Portal App',
    slug: 'app-portal',
    description: 'Next.js 15 SSG+ISR public site: theme pages, composed pages, SEO, revalidation.',
    owned_files: [
      'apps/portal/app/layout.tsx',
      'apps/portal/app/globals.css',
      'apps/portal/app/sitemap.ts',
      'apps/portal/app/[[...slug]]/page.tsx',
      'apps/portal/app/themes/[slug]/page.tsx',
      'apps/portal/app/_components/block-renderer.tsx',
      'apps/portal/app/api/revalidate/route.ts',
      'apps/portal/lib/blocks.ts',
      'apps/portal/lib/global-elements.ts',
      'apps/portal/lib/hooks.ts',
      'apps/portal/lib/optimize-images.ts',
      'apps/portal/lib/supabase.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-ui'],
    known_gaps: [
      'note: [[...slug]] catch-all handles composed pages — new pages need revalidation',
      'important: hook resolution ({{price}} → theme.meta.price) is build-time string replacement in RSC',
    ],
  },

  'studio-blocks': {
    name: 'Studio Block Pipeline',
    slug: 'studio-blocks',
    description: 'Block editor, import panel, CSS token scanner, token map — the processing pipeline.',
    owned_files: [
      'apps/studio/src/pages/block-editor.tsx',
      'apps/studio/src/components/block-import-panel.tsx',
      'apps/studio/src/lib/block-processor.ts',
      'apps/studio/src/lib/token-map.ts',
      // WP-027 Phase 1: Responsive tab scaffold (source + PARITY contract).
      'apps/studio/src/pages/block-editor/responsive/ResponsiveTab.tsx',
      'apps/studio/src/pages/block-editor/responsive/ResponsivePreview.tsx',
      'apps/studio/src/pages/block-editor/responsive/PreviewPanel.tsx',
      'apps/studio/src/pages/block-editor/responsive/SuggestionList.tsx',
      'apps/studio/src/pages/block-editor/responsive/SuggestionRow.tsx',
      'apps/studio/src/pages/block-editor/responsive/session-state.ts',
      'apps/studio/src/pages/block-editor/responsive/preview-assets.ts',
      'apps/studio/src/pages/block-editor/responsive/PARITY.md',
      // WP-027 Phase 1: Responsive tab tests (1 real + 3 describe.skip stubs per
      // pkg-block-forge-core precedent; stubs land real tests in Phases 2/3/4).
      'apps/studio/src/pages/block-editor/responsive/__tests__/session-state.test.ts',
      'apps/studio/src/pages/block-editor/responsive/__tests__/preview-assets.test.ts',
      'apps/studio/src/pages/block-editor/responsive/__tests__/suggestion-row.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/__tests__/integration.test.tsx',
      // WP-028 Phase 1: TweakPanel + VariantsDrawer placeholder scaffolds
      // (cross-surface parity mirrors with tools/block-forge; Phase 2/3 fill them in).
      'apps/studio/src/pages/block-editor/responsive/TweakPanel.tsx',
      'apps/studio/src/pages/block-editor/responsive/VariantsDrawer.tsx',
      'apps/studio/src/pages/block-editor/responsive/__tests__/TweakPanel.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/__tests__/VariantsDrawer.test.tsx',
      // WP-029 Phase 1 (Task A): variant CSS scoping advisory validator + unit pins.
      'apps/studio/src/pages/block-editor/responsive/validateVariantCss.ts',
      'apps/studio/src/pages/block-editor/responsive/__tests__/validateVariantCss.test.ts',
      // WP-033 Phase 5 OQ1: live-rerender test pins displayBlock follows watchedFormCode.
      'apps/studio/src/pages/block-editor/responsive/__tests__/responsive-tab-live-rerender.test.tsx',
      // WP-033 Phase 4: Inspector cross-surface mirror (Studio side). Sibling
      // subdirectory `inspector/` per Phase 4 Ruling 1 (REIMPLEMENT, not extract).
      // 5 component files + 2 hook files + 2 lib helpers + 10 test files = 19.
      'apps/studio/src/pages/block-editor/responsive/inspector/Inspector.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/InspectorPanel.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/PropertyRow.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/BreadcrumbNav.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/TokenChip.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/hooks/useInspectorPerBpValues.ts',
      'apps/studio/src/pages/block-editor/responsive/inspector/hooks/useChipDetection.ts',
      'apps/studio/src/pages/block-editor/responsive/inspector/lib/dispatchInspectorEdit.ts',
      'apps/studio/src/pages/block-editor/responsive/inspector/lib/css-mutate.ts',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/Inspector.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/InspectorPanel.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/PropertyRow.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/BreadcrumbNav.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/TokenChip.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/useInspectorPerBpValues.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/useChipDetection.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/inspector-cell-edit.test.tsx',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/dispatchInspectorEdit.test.ts',
      'apps/studio/src/pages/block-editor/responsive/inspector/__tests__/css-mutate.test.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-validators', 'pkg-api-client', 'pkg-ui', 'pkg-block-forge-core', 'studio-core'],
    known_gaps: [
      'important: block-processor depends on token-map — if tokens.css changes, token-map may need updates',
      'note: processing is 100% client-side — no API calls for token analysis',
    ],
  },

  'studio-core': {
    name: 'Studio App Shell & CRUD',
    slug: 'studio-core',
    description: 'Vite SPA shell, routing, layouts, auth pages, and entity CRUD for themes/blocks/templates/pages/global-elements.',
    owned_files: [
      // entry + app
      'apps/studio/src/main.tsx',
      'apps/studio/src/app.tsx',
      'apps/studio/src/globals.css',
      // layouts
      'apps/studio/src/layouts/app-layout.tsx',
      'apps/studio/src/layouts/auth-layout.tsx',
      // pages (12, excl block-editor which is in studio-blocks)
      'apps/studio/src/pages/blocks-list.tsx',
      'apps/studio/src/pages/elements-list.tsx',
      'apps/studio/src/pages/global-elements-settings.tsx',
      'apps/studio/src/pages/slots-list.tsx',
      'apps/studio/src/pages/login.tsx',
      'apps/studio/src/pages/media.tsx',
      'apps/studio/src/pages/not-found.tsx',
      'apps/studio/src/pages/page-editor.tsx',
      'apps/studio/src/pages/pages-list.tsx',
      'apps/studio/src/pages/template-editor.tsx',
      'apps/studio/src/pages/templates-list.tsx',
      'apps/studio/src/pages/theme-editor.tsx',
      'apps/studio/src/pages/themes-list.tsx',
      'apps/studio/src/pages/theme-meta.tsx',
      'apps/studio/src/components/taxonomy-list.tsx',
      'apps/studio/src/components/taxonomy-picker-modal.tsx',
      // components (20, excl block-import-panel which is in studio-blocks)
      'apps/studio/src/components/block-picker-modal.tsx',
      'apps/studio/src/components/block-preview.tsx',
      'apps/studio/src/components/char-counter.tsx',
      'apps/studio/src/components/delete-confirm-modal.tsx',
      'apps/studio/src/components/editor-footer.tsx',
      'apps/studio/src/components/editor-sidebar.tsx',
      'apps/studio/src/components/icon-picker-modal.tsx',
      'apps/studio/src/components/preset-bar.tsx',
      'apps/studio/src/components/tag-input.tsx',
      'apps/studio/src/components/error-boundary.tsx',
      'apps/studio/src/components/form-section.tsx',
      'apps/studio/src/components/pagination.tsx',
      'apps/studio/src/components/position-grid.tsx',
      'apps/studio/src/components/sidebar.tsx',
      'apps/studio/src/components/status-badge.tsx',
      'apps/studio/src/components/template-picker.tsx',
      'apps/studio/src/components/theme-card.tsx',
      'apps/studio/src/components/themes-table.tsx',
      'apps/studio/src/components/themes-toolbar.tsx',
      'apps/studio/src/components/toast.tsx',
      'apps/studio/src/components/topbar.tsx',
      // lib (7, excl block-processor + token-map which are in studio-blocks)
      'apps/studio/src/lib/block-api.ts',
      'apps/studio/src/lib/form-defaults.ts',
      'apps/studio/src/lib/format.ts',
      'apps/studio/src/lib/page-api.ts',
      'apps/studio/src/lib/queries.ts',
      'apps/studio/src/lib/supabase.ts',
      'apps/studio/src/lib/template-api.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-auth', 'pkg-validators', 'pkg-api-client', 'pkg-ui'],
    known_gaps: [
      'important: block-api.ts exports shared authHeaders/parseError used by ALL entity API wrappers',
      'note: elements-list.tsx is blocks filtered by block_type === "element" — not a separate entity',
      'note: all editors duplicate inputStyle/labelStyle inline objects — no shared style component',
    ],
  },

  'app-admin': {
    name: 'Admin App',
    slug: 'app-admin',
    description: 'Admin-only Vite SPA: Overview, Staff & Roles, User Inspector, Audit Log, System Health. Requires admin staff_role.',
    owned_files: [
      'apps/admin/src/main.tsx',
      'apps/admin/src/app.tsx',
      'apps/admin/src/globals.css',
      'apps/admin/src/lib/supabase.ts',
      'apps/admin/src/lib/api.ts',
      'apps/admin/src/layouts/app-layout.tsx',
      'apps/admin/src/layouts/auth-layout.tsx',
      'apps/admin/src/pages/login.tsx',
      'apps/admin/src/pages/auth-callback.tsx',
      'apps/admin/src/pages/not-found.tsx',
      'apps/admin/src/pages/overview.tsx',
      'apps/admin/src/pages/staff.tsx',
      'apps/admin/src/pages/user-list.tsx',
      'apps/admin/src/pages/user-inspector.tsx',
      'apps/admin/src/pages/audit-log.tsx',
      'apps/admin/src/pages/system-health.tsx',
      'apps/admin/src/components/sidebar.tsx',
      'apps/admin/src/components/topbar.tsx',
      'apps/admin/src/components/page-header.tsx',
      'apps/admin/src/components/avatar-initials.tsx',
      'apps/admin/src/components/status-badge.tsx',
      'apps/admin/src/components/stat-card.tsx',
      'apps/admin/src/components/date-range-toggle.tsx',
      'apps/admin/src/components/activation-event.tsx',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-auth', 'pkg-ui'],
    known_gaps: [
      'note: User Inspector has two routes: /users (list) and /users/:id (detail)',
      'note: DateRangeToggle on Overview is visual only — stats API does not accept date range params',
    ],
  },

  'app-dashboard': {
    name: 'Dashboard App',
    slug: 'app-dashboard',
    description: 'Customer-facing Vite SPA: My Themes (real data), My Account (real data), Support/Downloads (mock). Any authenticated user.',
    owned_files: [
      'apps/dashboard/src/main.tsx',
      'apps/dashboard/src/app.tsx',
      'apps/dashboard/src/globals.css',
      'apps/dashboard/src/lib/supabase.ts',
      'apps/dashboard/src/lib/api.ts',
      'apps/dashboard/src/layouts/app-layout.tsx',
      'apps/dashboard/src/layouts/auth-layout.tsx',
      'apps/dashboard/src/pages/login.tsx',
      'apps/dashboard/src/pages/auth-callback.tsx',
      'apps/dashboard/src/pages/not-found.tsx',
      'apps/dashboard/src/pages/my-themes.tsx',
      'apps/dashboard/src/pages/my-account.tsx',
      'apps/dashboard/src/pages/licenses.tsx',
      'apps/dashboard/src/pages/support.tsx',
      'apps/dashboard/src/pages/downloads.tsx',
      'apps/dashboard/src/components/sidebar.tsx',
      'apps/dashboard/src/components/topbar.tsx',
      'apps/dashboard/src/components/theme-card.tsx',
      'apps/dashboard/src/components/stat-card.tsx',
      'apps/dashboard/src/components/capabilities-table.tsx',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-auth', 'pkg-ui'],
    known_gaps: [
      'note: Support and Downloads are mock stubs — real implementation in future phases',
      'note: Deactivate link, How to install links not functional (no backend yet)',
      'note: Bundled plugins derived from theme meta.compatible_plugins — may be empty',
    ],
  },

  'app-api': {
    name: 'Hono API',
    slug: 'app-api',
    description: 'Hono on Cloudflare Workers: CRUD routes, auth middleware, R2 upload, revalidation. Only place secrets live.',
    owned_files: [
      'apps/api/src/index.ts',
      'apps/api/src/env.ts',
      'apps/api/src/lib/supabase.ts',
      'apps/api/src/middleware/auth.ts',
      'apps/api/src/middleware/role.ts',
      'apps/api/src/routes/blocks.ts',
      'apps/api/src/routes/global-elements.ts',
      'apps/api/src/routes/health.ts',
      'apps/api/src/routes/pages.ts',
      'apps/api/src/routes/revalidate.ts',
      'apps/api/src/routes/templates.ts',
      'apps/api/src/routes/upload.ts',
      'apps/api/src/routes/icons.ts',
      'apps/api/src/routes/presets.ts',
      'apps/api/src/routes/licenses.ts',
      'apps/api/src/routes/admin.ts',
      'apps/api/src/routes/user.ts',
    ],
    owned_tables: [],
    owned_routes: [
      'apps/api/src/routes/blocks.ts',
      'apps/api/src/routes/global-elements.ts',
      'apps/api/src/routes/health.ts',
      'apps/api/src/routes/icons.ts',
      'apps/api/src/routes/presets.ts',
      'apps/api/src/routes/pages.ts',
      'apps/api/src/routes/revalidate.ts',
      'apps/api/src/routes/templates.ts',
      'apps/api/src/routes/upload.ts',
      'apps/api/src/routes/licenses.ts',
      'apps/api/src/routes/admin.ts',
      'apps/api/src/routes/user.ts',
    ],
    public_entrypoints: [],
    allowed_imports_from: ['pkg-db', 'pkg-validators', 'pkg-auth'],
    known_gaps: [
      'important: secrets boundary — Envato key, Resend key, Claude API key, R2 creds, service_role ONLY here',
      'note: supabase client uses service_role key — bypasses RLS',
    ],
  },

  'app-command-center': {
    name: 'Command Center App',
    slug: 'app-command-center',
    description: 'Internal project management tool. Own dark theme, fully isolated from Portal DS.',
    owned_files: [
      // app routes
      'apps/command-center/app/layout.tsx',
      'apps/command-center/app/page.tsx',
      'apps/command-center/app/globals.css',
      'apps/command-center/app/architecture/page.tsx',
      'apps/command-center/app/architecture/[id]/page.tsx',
      'apps/command-center/app/architecture/ArchitectureTabs.tsx',
      'apps/command-center/app/components/page.tsx',
      'apps/command-center/app/components/[id]/page.tsx',
      'apps/command-center/app/components/[id]/component-preview.tsx',
      'apps/command-center/app/content/page.tsx',
      'apps/command-center/app/dependencies/page.tsx',
      'apps/command-center/app/phases/page.tsx',
      'apps/command-center/app/phases/[id]/page.tsx',
      // components
      'apps/command-center/components/ADRViewer.tsx',
      'apps/command-center/components/ActivityFeed.tsx',
      'apps/command-center/components/AppCard.tsx',
      'apps/command-center/components/BurndownChart.tsx',
      'apps/command-center/components/ContentOverview.tsx',
      'apps/command-center/components/DependencyGraph.tsx',
      'apps/command-center/components/DesignSystemProgress.tsx',
      'apps/command-center/components/GlobalSearch.tsx',
      'apps/command-center/components/InfraChecklist.tsx',
      'apps/command-center/components/PhaseCard.tsx',
      'apps/command-center/components/PhaseTimeline.tsx',
      'apps/command-center/components/PhaseTrackerClient.tsx',
      'apps/command-center/components/Sidebar.tsx',
      'apps/command-center/components/TaskDetailSheet.tsx',
      'apps/command-center/components/TaskFilters.tsx',
      'apps/command-center/components/TaskTable.tsx',
      'apps/command-center/components/TasksView.tsx',
      'apps/command-center/components/ThemeStatusTable.tsx',
      // ui
      'apps/command-center/ui/Card.tsx',
      'apps/command-center/ui/DonutChart.tsx',
      'apps/command-center/ui/Input.tsx',
      'apps/command-center/ui/ProgressBar.tsx',
      'apps/command-center/ui/Select.tsx',
      'apps/command-center/ui/StatusBadge.tsx',
      'apps/command-center/ui/StatusDots.tsx',
      'apps/command-center/ui/TokenCoveragePanel.tsx',
      // lib
      'apps/command-center/lib/data.ts',
      'apps/command-center/lib/phase-sync.ts',
      'apps/command-center/lib/types.ts',
      'apps/command-center/lib/utils.ts',
      // cli
      'apps/command-center/cli/report.ts',
      'apps/command-center/cli/scan.ts',
      // theme
      'apps/command-center/theme/utils.ts',
      // types
      'apps/command-center/types/tailwindcss.d.ts',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: [],
    known_gaps: [
      'note: has own dark zinc theme — do NOT apply Portal DS tokens',
      'note: ui/ directory is CC-local components — not @cmsmasters/ui',
    ],
    policy: 'isolated',
  },

  'infra-tooling': {
    name: 'Infrastructure & Tooling',
    slug: 'infra-tooling',
    description: 'Monorepo config, context docs, workplans, dev tools. Non-code meta domain.',
    owned_files: [
      '.context/BRIEF.md',
      '.context/ADR_DIGEST.md',
      '.context/CONVENTIONS.md',
      '.context/LAYER_0_SPEC.md',
      '.context/ROADMAP.md',
      '.context/SKILL.md',
      '.context/DESKTOP_SKILL.md',
      '.context/FIGMA_DESIGN_WORKFLOW.md',
      'tools/test-scanner.ts',
      'tools/sync-tokens/README.md',
      'tools/sync-tokens/figma.config.json',
      'tools/layout-maker/runtime/lib/css-generator.ts',
      'tools/layout-maker/runtime/lib/css-generator.test.ts',
      'tools/block-forge/package.json',
      'tools/block-forge/tsconfig.json',
      'tools/block-forge/vite.config.ts',
      'tools/block-forge/tailwind.config.ts',
      'tools/block-forge/postcss.config.cjs',
      'tools/block-forge/PARITY.md',
      'tools/block-forge/index.html',
      'tools/block-forge/src/main.tsx',
      'tools/block-forge/src/App.tsx',
      'tools/block-forge/src/types.ts',
      'tools/block-forge/src/vite-env.d.ts',
      'tools/block-forge/src/globals.css',
      'tools/block-forge/src/components/BlockPicker.tsx',
      'tools/block-forge/src/components/PreviewPanel.tsx',
      'tools/block-forge/src/components/PreviewTriptych.tsx',
      'tools/block-forge/src/components/SuggestionList.tsx',
      'tools/block-forge/src/components/SuggestionRow.tsx',
      'tools/block-forge/src/components/StatusBar.tsx',
      // WP-028 Phase 1: TweakPanel + VariantsDrawer placeholder scaffolds
      // (cross-surface parity mirrors with apps/studio; Phase 2/3 fill them in).
      'tools/block-forge/src/components/TweakPanel.tsx',
      'tools/block-forge/src/components/VariantsDrawer.tsx',
      'tools/block-forge/src/components/FluidModeControl.tsx',
      // WP-033 Phase 1: Inspector orchestrator + InspectorPanel UI shell.
      // DevTools-style hover/pin replacement for TweakPanel — block-forge first;
      // Studio mirror lands in Phase 4 per Ruling D (REIMPLEMENT, not extract).
      'tools/block-forge/src/components/Inspector.tsx',
      'tools/block-forge/src/components/InspectorPanel.tsx',
      // WP-033 Phase 2: BreadcrumbNav extract + PropertyRow component.
      // PropertyRow renders 12 MVP properties across 3 BP cells; Phase 3 wires
      // editing + token-chip detection into the structural slots reserved here.
      'tools/block-forge/src/components/BreadcrumbNav.tsx',
      'tools/block-forge/src/components/PropertyRow.tsx',
      // WP-033 Phase 3: TokenChip render component (in-use vs available modes).
      'tools/block-forge/src/components/TokenChip.tsx',
      // WP-033 Phase 3: hooks/ directory established this phase. Per-BP value
      // sourcing (3 hidden iframes, Ruling E Option A) + chip detection
      // (Option B-subset PostCSS walk, Ruling 2).
      'tools/block-forge/src/hooks/useInspectorPerBpValues.ts',
      'tools/block-forge/src/hooks/useChipDetection.ts',
      'tools/block-forge/src/lib/fluid-mode.ts',
      'tools/block-forge/src/lib/file-io.ts',
      'tools/block-forge/src/lib/paths.ts',
      'tools/block-forge/src/lib/preview-assets.ts',
      'tools/block-forge/src/lib/api-client.ts',
      'tools/block-forge/src/lib/useAnalysis.ts',
      'tools/block-forge/src/lib/session.ts',
      'tools/block-forge/src/__tests__/file-io.test.ts',
      'tools/block-forge/src/__tests__/preview-assets.test.ts',
      'tools/block-forge/src/__tests__/integration.test.tsx',
      'tools/block-forge/src/__tests__/session.test.ts',
      'tools/block-forge/src/__tests__/fluid-mode.test.ts',
      // WP-028 Phase 1: parity tests for TweakPanel + VariantsDrawer placeholders.
      'tools/block-forge/src/__tests__/TweakPanel.test.tsx',
      'tools/block-forge/src/__tests__/VariantsDrawer.test.tsx',
      // WP-033 Phase 1: Inspector unit tests + InspectorPanel snapshot.
      'tools/block-forge/src/__tests__/Inspector.test.tsx',
      'tools/block-forge/src/__tests__/InspectorPanel.test.tsx',
      // WP-033 Phase 2: BreadcrumbNav + PropertyRow tests.
      'tools/block-forge/src/__tests__/BreadcrumbNav.test.tsx',
      'tools/block-forge/src/__tests__/PropertyRow.test.tsx',
      // WP-033 Phase 3: cell-edit + per-BP hook + chip detection + TokenChip
      // + slider regression pin (the bug WP-033 was born to fix).
      'tools/block-forge/src/__tests__/inspector-cell-edit.test.tsx',
      'tools/block-forge/src/__tests__/useInspectorPerBpValues.test.tsx',
      'tools/block-forge/src/__tests__/useChipDetection.test.tsx',
      'tools/block-forge/src/__tests__/TokenChip.test.tsx',
      'tools/block-forge/src/__tests__/slider-bug-regression.test.ts',
      // WP-030 Phase 1: Responsive Tokens Editor scaffold (Vite app on :7703).
      // README.md and .gitignore are git-tracked but excluded from manifest per
      // block-forge precedent (meta files not registered as owned source).
      'tools/responsive-tokens-editor/package.json',
      'tools/responsive-tokens-editor/tsconfig.json',
      'tools/responsive-tokens-editor/vite.config.ts',
      'tools/responsive-tokens-editor/tailwind.config.ts',
      'tools/responsive-tokens-editor/postcss.config.cjs',
      'tools/responsive-tokens-editor/index.html',
      'tools/responsive-tokens-editor/PARITY.md',
      'tools/responsive-tokens-editor/src/main.tsx',
      'tools/responsive-tokens-editor/src/App.tsx',
      'tools/responsive-tokens-editor/src/types.ts',
      'tools/responsive-tokens-editor/src/vite-env.d.ts',
      'tools/responsive-tokens-editor/src/globals.css',
      // WP-030 Phase 2: Config schema + math engine. Snapshot file
      // (__snapshots__/generator.test.ts.snap) is git-tracked but excluded
      // from manifest per block-forge precedent (snapshot artifacts not registered).
      'tools/responsive-tokens-editor/src/lib/defaults.ts',
      'tools/responsive-tokens-editor/src/lib/generator.ts',
      'tools/responsive-tokens-editor/src/lib/validate.ts',
      'tools/responsive-tokens-editor/src/lib/config-io.ts',
      'tools/responsive-tokens-editor/src/__tests__/generator.test.ts',
      'tools/responsive-tokens-editor/src/__tests__/defaults.test.ts',
      'tools/responsive-tokens-editor/src/__tests__/validate.test.ts',
      // WP-030 Phase 3: Global Scale UI — 4 components + 4 tests + setupTests.
      // All run in jsdom via per-file `// @vitest-environment jsdom` directive
      // (PF.7 — block-forge precedent; NOT global env).
      'tools/responsive-tokens-editor/src/setupTests.ts',
      'tools/responsive-tokens-editor/src/components/GlobalScaleConfig.tsx',
      'tools/responsive-tokens-editor/src/components/WcagBanner.tsx',
      'tools/responsive-tokens-editor/src/components/ResetButton.tsx',
      'tools/responsive-tokens-editor/src/components/LoadStatusBadge.tsx',
      'tools/responsive-tokens-editor/src/__tests__/App.test.tsx',
      'tools/responsive-tokens-editor/src/__tests__/GlobalScaleConfig.test.tsx',
      'tools/responsive-tokens-editor/src/__tests__/WcagBanner.test.tsx',
      'tools/responsive-tokens-editor/src/__tests__/ResetButton.test.tsx',
      // WP-030 Phase 4: Token Preview Grid + Per-Token Override Editor.
      // Inline-expand pattern (PF.15 — @cmsmasters/ui dep deferred).
      // valueAtViewport pure-fn extracted for testability (PF.19).
      'tools/responsive-tokens-editor/src/components/TokenPreviewGrid.tsx',
      'tools/responsive-tokens-editor/src/components/TokenOverrideEditor.tsx',
      'tools/responsive-tokens-editor/src/__tests__/TokenPreviewGrid.test.tsx',
      'tools/responsive-tokens-editor/src/__tests__/TokenOverrideEditor.test.tsx',
      // WP-030 Phase 5: Container Widths Editor + Live Preview Row.
      // 3-BP schema extension (PF.22-PF.24); iframe srcdoc preview (PF.25-PF.26).
      // PostCSS @import order fix BAKED into globals.css (PF.21).
      'tools/responsive-tokens-editor/src/components/ContainerWidthsEditor.tsx',
      'tools/responsive-tokens-editor/src/components/LivePreviewRow.tsx',
      'tools/responsive-tokens-editor/src/__tests__/ContainerWidthsEditor.test.tsx',
      'tools/responsive-tokens-editor/src/__tests__/LivePreviewRow.test.tsx',
      'nx.json',
    ],
    owned_tables: [],
    owned_routes: [],
    public_entrypoints: [],
    allowed_imports_from: [],
    known_gaps: [
      'note: workplan/*.md and tools/studio-mockups/*.html tracked as directory — not individual files',
    ],
    policy: 'meta',
  },
}

