import type { LayoutConfig } from './config-schema.js'
import type { TokenMap } from './token-parser.js'

/** Resolve a token reference or passthrough a raw value */
function resolveValue(tokenOrValue: string, tokens: TokenMap): string {
  if (tokenOrValue === '0') return '0'
  if (tokenOrValue.endsWith('px')) return tokenOrValue
  const val = tokens[tokenOrValue]
  if (!val) throw new Error(`Cannot resolve token: ${tokenOrValue}`)
  return val
}

/** CSS var prefix for a slot name: --sl-{name} */
function slotVarPrefix(name: string): string {
  return `--sl-${name}`
}

/** Resolve visual slot params into CSS custom property map */
function resolveSlotVars(
  name: string,
  slot: {
    gap?: string
    'max-width'?: string
    'padding-x'?: string
    'padding-top'?: string
    'padding-bottom'?: string
    padding?: string
    align?: string
  },
  tokens: TokenMap,
): Record<string, string> {
  const pf = slotVarPrefix(name)
  const vars: Record<string, string> = {}

  if (slot['max-width']) vars[`${pf}-mw`] = slot['max-width']
  if (slot.gap) vars[`${pf}-gap`] = resolveValue(slot.gap, tokens)

  // Padding: prefer split fields, fall back to legacy shorthand
  const padX = slot['padding-x'] ?? slot.padding
  const padTop = slot['padding-top'] ?? slot.padding
  const padBottom = slot['padding-bottom'] ?? slot.padding
  if (padX) vars[`${pf}-px`] = resolveValue(padX, tokens)
  if (padTop) vars[`${pf}-pt`] = resolveValue(padTop, tokens)
  if (padBottom) vars[`${pf}-pb`] = resolveValue(padBottom, tokens)

  if (slot.align) vars[`${pf}-al`] = slot.align

  return vars
}

/** Sort breakpoints by min-width descending (desktop first) */
function sortBreakpoints(
  grid: LayoutConfig['grid'],
): [string, LayoutConfig['grid'][string]][] {
  return Object.entries(grid).sort(
    (a, b) =>
      parseInt(b[1]['min-width'], 10) - parseInt(a[1]['min-width'], 10),
  )
}

// eslint-disable-next-line sonarjs/cognitive-complexity
export function generateCSS(config: LayoutConfig, tokens: TokenMap): string {
  const out: string[] = []
  const bps = sortBreakpoints(config.grid)
  const [defaultBpName, defaultGrid] = bps[0]

  const hasDrawers = bps.some(([, g]) => g.sidebars === 'drawer')
  const sidebarSlots = Object.keys(config.slots).filter((n) =>
    n.includes('sidebar'),
  )

  // Determine drawer sides needed
  let needLeftDrawer = false
  let needRightDrawer = false
  if (hasDrawers) {
    for (const [, g] of bps) {
      if (g.sidebars === 'drawer') {
        const pos = g['drawer-position'] ?? 'both'
        if (pos === 'left' || pos === 'both') needLeftDrawer = true
        if (pos === 'right' || pos === 'both') needRightDrawer = true
      }
    }
  }

  // ── Header ──
  out.push(`/* Layout: ${config.name} */`)
  out.push(`/* Scope: ${config.scope} */`)
  out.push('/* Generated by Layout Maker — do not edit manually */')
  out.push('')

  // ── Layout frame ──
  out.push('/* ── Layout frame ── */')
  out.push('.layout-frame {')
  out.push('  width: 100%;')
  if (defaultGrid['max-width']) {
    out.push(`  max-width: ${defaultGrid['max-width']};`)
  }
  if (defaultGrid.center) {
    out.push('  margin: 0 auto;')
  }
  out.push('}')
  out.push('')

  // ── Default grid ──
  const defaultCols = Object.values(defaultGrid.columns).join(' ')
  const defaultGap = defaultGrid['column-gap']
    ? resolveValue(defaultGrid['column-gap'], tokens)
    : '0'

  out.push(
    `/* ── Grid: ${defaultBpName} (${defaultGrid['min-width']}+) ── */`,
  )
  out.push('.layout-grid {')
  out.push('  display: grid;')
  out.push(`  grid-template-columns: ${defaultCols};`)
  if (defaultGap !== '0') {
    out.push(`  column-gap: ${defaultGap};`)
  }
  out.push('}')
  out.push('')

  // ── Slot outer styles (role-level: sticky, padding, min-height) ──
  for (const [name, slot] of Object.entries(config.slots)) {
    const rules: string[] = []

    // Outer is always flex-column so .slot-inner can position itself
    rules.push('display: flex')
    rules.push('flex-direction: column')

    if (slot.sticky) {
      rules.push('position: sticky')
      rules.push('top: 0')
      if (slot['z-index'] != null) {
        rules.push(`z-index: ${slot['z-index']}`)
      }
    }

    if (slot['min-height']) {
      rules.push(`min-height: ${slot['min-height']}`)
    }
    if (slot['margin-top']) {
      rules.push(`margin-top: ${resolveValue(slot['margin-top'], tokens)}`)
    }

    out.push(`/* ── Slot: ${name} ── */`)
    out.push(`[data-slot="${name}"] {`)
    for (const rule of rules) {
      out.push(`  ${rule};`)
    }
    out.push('}')
    out.push('')
  }

  // ── Slot inner CSS custom properties (base = desktop) ──
  out.push('/* ── Slot inner vars (base) ── */')
  out.push(':root {')
  for (const [name, slot] of Object.entries(config.slots)) {
    const vars = resolveSlotVars(name, slot, tokens)
    for (const [prop, val] of Object.entries(vars)) {
      out.push(`  ${prop}: ${val};`)
    }
  }
  out.push('}')
  out.push('')

  // Generic slot-inner base rule
  out.push('[data-slot] > .slot-inner {')
  out.push('  display: flex;')
  out.push('  flex-direction: column;')
  out.push('  width: 100%;')
  out.push('  flex: 1 0 auto;')
  out.push('}')
  out.push('')

  // Per-slot inner rules (consume vars, static across layouts)
  for (const name of Object.keys(config.slots)) {
    const pf = slotVarPrefix(name)
    out.push(`[data-slot="${name}"] > .slot-inner {`)
    out.push(`  max-width: var(${pf}-mw, none);`)
    out.push(`  padding: var(${pf}-pt, 0) var(${pf}-px, 0) var(${pf}-pb, 0);`)
    out.push(`  gap: var(${pf}-gap, 0);`)
    out.push(`  align-self: var(${pf}-al, stretch);`)
    out.push(`  margin-inline: auto;`)
    out.push('}')
    out.push('')
  }

  // ── Drawer base CSS (always visible, off-screen by default) ──
  if (hasDrawers) {
    const firstDrawerBp = bps.find(([, g]) => g.sidebars === 'drawer')
    const defaultDrawerWidth = firstDrawerBp?.[1]['drawer-width'] ?? '280px'

    out.push('/* ── Drawer ── */')
    out.push('.layout-drawer {')
    out.push('  position: fixed;')
    out.push('  top: 0;')
    out.push('  left: 0;')
    out.push('  height: 100vh;')
    out.push(`  width: ${defaultDrawerWidth};`)
    out.push('  background: white;')
    out.push('  z-index: 1000;')
    out.push('  transform: translateX(-100%);')
    out.push('  transition: transform 0.3s ease;')
    out.push('  overflow-y: auto;')
    out.push('}')
    out.push('')
    out.push('.layout-drawer--right {')
    out.push('  right: 0;')
    out.push('  left: auto;')
    out.push('  transform: translateX(100%);')
    out.push('}')
    out.push('')
    out.push('.layout-drawer.open {')
    out.push('  transform: translateX(0);')
    out.push('}')
    out.push('')
    out.push('.layout-drawer-backdrop {')
    out.push('  position: fixed;')
    out.push('  inset: 0;')
    out.push('  background: rgba(0, 0, 0, 0.4);')
    out.push('  z-index: 999;')
    out.push('  opacity: 0;')
    out.push('  pointer-events: none;')
    out.push('  transition: opacity 0.3s ease;')
    out.push('}')
    out.push('')
    out.push('.layout-drawer-backdrop.open {')
    out.push('  opacity: 1;')
    out.push('  pointer-events: auto;')
    out.push('}')
    out.push('')
    out.push('.drawer-close {')
    out.push('  position: absolute;')
    out.push('  top: 8px;')
    out.push('  right: 8px;')
    out.push('  background: none;')
    out.push('  border: none;')
    out.push('  font-size: 24px;')
    out.push('  cursor: pointer;')
    out.push('  padding: 4px 8px;')
    out.push('}')
    out.push('')
    out.push('.drawer-trigger {')
    out.push('  display: none;')
    out.push('  position: fixed;')
    out.push('  top: 50%;')
    out.push('  transform: translateY(-50%);')
    out.push('  z-index: 998;')
    out.push('  background: white;')
    out.push('  border: 1px solid #ddd;')
    out.push('  padding: 8px;')
    out.push('  cursor: pointer;')
    out.push('  border-radius: 4px;')
    out.push('}')
    out.push('')

    if (needLeftDrawer) {
      out.push('.drawer-trigger--left {')
      out.push('  left: 8px;')
      out.push('}')
      out.push('')
    }

    if (needRightDrawer) {
      out.push('.drawer-trigger--right {')
      out.push('  right: 8px;')
      out.push('}')
      out.push('')
    }
  }

  // ── Responsive breakpoints ──
  for (let i = 1; i < bps.length; i++) {
    const [bpName, grid] = bps[i]
    const prevGrid = bps[i - 1][1]
    const maxWidth = parseInt(prevGrid['min-width'], 10) - 1

    out.push(
      `/* ── Grid: ${bpName} (${grid['min-width']} – ${maxWidth}px) ── */`,
    )
    out.push(`@media (max-width: ${maxWidth}px) {`)

    // Frame overrides
    const needsFrameReset = defaultGrid['max-width'] && !grid['max-width']
    const hasNewMaxWidth = !!grid['max-width']
    const centerChanged = defaultGrid.center && !grid.center

    if (needsFrameReset || hasNewMaxWidth || centerChanged) {
      out.push('  .layout-frame {')
      if (hasNewMaxWidth) {
        out.push(`    max-width: ${grid['max-width']};`)
      } else if (needsFrameReset) {
        out.push('    max-width: none;')
      }
      if (centerChanged) {
        out.push('    margin: 0;')
      } else if (grid.center) {
        out.push('    margin: 0 auto;')
      }
      out.push('  }')
      out.push('')
    }

    // Grid columns
    const cols = Object.values(grid.columns).join(' ')
    const gap = grid['column-gap']
      ? resolveValue(grid['column-gap'], tokens)
      : '0'

    out.push('  .layout-grid {')
    out.push(`    grid-template-columns: ${cols};`)
    if (gap !== '0') {
      out.push(`    column-gap: ${gap};`)
    } else {
      out.push('    column-gap: 0;')
    }
    out.push('  }')

    // Hide sidebar slots in drawer or hidden mode
    if ((grid.sidebars === 'drawer' || grid.sidebars === 'hidden') && sidebarSlots.length > 0) {
      out.push('')
      const selectors = sidebarSlots
        .map((n) => `  [data-slot="${n}"]`)
        .join(',\n')
      out.push(`${selectors} {`)
      out.push('    display: none;')
      out.push('  }')
    }

    // Show drawer triggers
    if (grid.sidebars === 'drawer') {
      out.push('')
      out.push('  .drawer-trigger {')
      out.push('    display: block;')
      out.push('  }')

      if (grid['drawer-width']) {
        out.push('')
        out.push('  .layout-drawer {')
        out.push(`    width: ${grid['drawer-width']};`)
        out.push('  }')
      }
    }

    // Per-bp slot inner var overrides
    if (grid.slots) {
      const bpVars: string[] = []
      for (const [slotName, overrides] of Object.entries(grid.slots)) {
        const vars = resolveSlotVars(slotName, overrides, tokens)
        for (const [prop, val] of Object.entries(vars)) {
          bpVars.push(`    ${prop}: ${val};`)
        }
      }
      if (bpVars.length > 0) {
        out.push('')
        out.push('  :root {')
        for (const v of bpVars) out.push(v)
        out.push('  }')
      }
    }

    out.push('}')
    out.push('')
  }

  return out.join('\n')
}
