import type { LayoutConfig } from './config-schema.js'
import type { TokenMap } from './token-parser.js'
import { hslTripletToHex } from './token-parser.js'

/** Resolve a token reference or passthrough a raw value */
function resolveValue(tokenOrValue: string, tokens: TokenMap): string {
  if (tokenOrValue === '0') return '0'
  if (tokenOrValue.endsWith('px')) return tokenOrValue
  const val = tokens[tokenOrValue]
  if (!val) throw new Error(`Cannot resolve token: ${tokenOrValue}`)
  return val
}

/** Resolve a background token ref to #RRGGBB hex or passthrough raw color. */
function resolveBackgroundCSS(value: string | undefined, tokens: TokenMap): string | undefined {
  if (!value) return undefined
  if (value.startsWith('--')) {
    const raw = tokens[value]
    if (!raw) return value
    return hslTripletToHex(raw) ?? raw
  }
  return value
}

/** CSS var prefix for a slot name: --sl-{name} */
function slotVarPrefix(name: string): string {
  return `--sl-${name}`
}

/** Resolve visual slot params into CSS custom property map */
function resolveSlotVars(
  name: string,
  slot: {
    gap?: string
    'max-width'?: string
    'padding-x'?: string
    'padding-top'?: string
    'padding-bottom'?: string
    padding?: string
    align?: string
  },
  tokens: TokenMap,
): Record<string, string> {
  const pf = slotVarPrefix(name)
  const vars: Record<string, string> = {}

  if (slot['max-width']) vars[`${pf}-mw`] = slot['max-width']
  if (slot.gap) vars[`${pf}-gap`] = resolveValue(slot.gap, tokens)

  // Padding: prefer split fields, fall back to legacy shorthand
  const padX = slot['padding-x'] ?? slot.padding
  const padTop = slot['padding-top'] ?? slot.padding
  const padBottom = slot['padding-bottom'] ?? slot.padding
  if (padX) vars[`${pf}-px`] = resolveValue(padX, tokens)
  if (padTop) vars[`${pf}-pt`] = resolveValue(padTop, tokens)
  if (padBottom) vars[`${pf}-pb`] = resolveValue(padBottom, tokens)

  if (slot.align) vars[`${pf}-al`] = slot.align

  return vars
}

/** Sort breakpoints by min-width descending (desktop first) */
function sortBreakpoints(
  grid: LayoutConfig['grid'],
): [string, LayoutConfig['grid'][string]][] {
  return Object.entries(grid).sort(
    (a, b) =>
      parseInt(b[1]['min-width'], 10) - parseInt(a[1]['min-width'], 10),
  )
}

// eslint-disable-next-line sonarjs/cognitive-complexity
export function generateCSS(config: LayoutConfig, tokens: TokenMap): string {
  const out: string[] = []
  const bps = sortBreakpoints(config.grid)
  const [defaultBpName, defaultGrid] = bps[0]

  const sidebarSlots = Object.keys(config.slots).filter((n) =>
    n.includes('sidebar'),
  )

  // Detect drawer usage: grid-level sidebars OR per-slot visibility:'drawer'
  const hasDrawers = bps.some(([, g]) =>
    g.sidebars === 'drawer' ||
    Object.values(g.slots ?? {}).some((s) => s.visibility === 'drawer'),
  )

  // Determine drawer sides needed
  let needLeftDrawer = false
  let needRightDrawer = false
  if (hasDrawers) {
    for (const [, g] of bps) {
      if (g.sidebars === 'drawer') {
        const pos = g['drawer-position'] ?? 'both'
        if (pos === 'left' || pos === 'both') needLeftDrawer = true
        if (pos === 'right' || pos === 'both') needRightDrawer = true
      }
      // Per-slot drawer: check which sidebar slots have visibility:'drawer'
      for (const [slotName, slotOverride] of Object.entries(g.slots ?? {})) {
        if (slotOverride.visibility === 'drawer') {
          if (slotName.includes('left')) needLeftDrawer = true
          if (slotName.includes('right')) needRightDrawer = true
        }
      }
    }
  }

  // ── Header ──
  out.push(`/* Layout: ${config.name} */`)
  out.push(`/* Scope: ${config.scope} */`)
  out.push('/* Generated by Layout Maker — do not edit manually */')
  out.push('')

  // ── Layout frame ──
  out.push('/* ── Layout frame ── */')
  out.push('.layout-frame {')
  out.push('  width: 100%;')
  if (defaultGrid['max-width']) {
    out.push(`  max-width: ${defaultGrid['max-width']};`)
  }
  if (defaultGrid.center) {
    out.push('  margin: 0 auto;')
  }
  out.push('}')
  out.push('')

  // ── Layout-level background (applied to html+body so it fills the viewport) ──
  const layoutBg = resolveBackgroundCSS(config.background, tokens)
  if (layoutBg) {
    out.push('/* ── Layout background ── */')
    out.push('html, body {')
    out.push(`  background: ${layoutBg};`)
    out.push('}')
    out.push('')
  }

  // Collect nested children — these render inside their parent, not as grid columns
  const nestedChildren = new Set<string>()
  for (const s of Object.values(config.slots)) {
    const nl = s['nested-slots']
    if (Array.isArray(nl)) nl.forEach((c: string) => nestedChildren.add(c))
  }

  // ── Default grid ──
  const defaultCols = Object.entries(defaultGrid.columns)
    .filter(([name]) => !nestedChildren.has(name))
    .map(([, w]) => w).join(' ')
  const defaultGap = defaultGrid['column-gap']
    ? resolveValue(defaultGrid['column-gap'], tokens)
    : '0'

  out.push(
    `/* ── Grid: ${defaultBpName} (${defaultGrid['min-width']}+) ── */`,
  )
  out.push('.layout-grid {')
  out.push('  display: grid;')
  out.push(`  grid-template-columns: ${defaultCols};`)
  if (defaultGap !== '0') {
    out.push(`  column-gap: ${defaultGap};`)
  }
  out.push('}')
  out.push('')

  // ── Slot outer styles (role-level: sticky, padding, min-height) ──
  for (const [name, slot] of Object.entries(config.slots)) {
    const rules: string[] = []

    // Outer is always flex-column so .slot-inner can position itself
    rules.push('display: flex')
    rules.push('flex-direction: column')

    if (slot.sticky) {
      rules.push('position: sticky')
      rules.push('top: 0')
      if (slot['z-index'] != null) {
        rules.push(`z-index: ${slot['z-index']}`)
      }
    }

    if (slot['min-height']) {
      rules.push(`min-height: ${slot['min-height']}`)
    }
    if (slot['margin-top']) {
      rules.push(`margin-top: ${resolveValue(slot['margin-top'], tokens)}`)
    }
    const slotBg = resolveBackgroundCSS(slot.background, tokens)
    if (slotBg) {
      rules.push(`background: ${slotBg}`)
    }

    // Border
    const borderSides = slot['border-sides']?.split(',') ?? []
    if (borderSides.length > 0) {
      const borderWidth = slot['border-width'] ?? '1px'
      const borderColorHex = resolveBackgroundCSS(slot['border-color'], tokens) ?? '#e2e8f0'
      rules.push('border: none')
      for (const side of borderSides) {
        rules.push(`border-${side}: ${borderWidth} solid ${borderColorHex}`)
      }
    }

    out.push(`/* ── Slot: ${name} ── */`)
    out.push(`[data-slot="${name}"] {`)
    for (const rule of rules) {
      out.push(`  ${rule};`)
    }
    out.push('}')
    out.push('')
  }

  // ── Slot inner CSS custom properties (base = desktop) ──
  out.push('/* ── Slot inner vars (base) ── */')
  out.push(':root {')
  for (const [name, slot] of Object.entries(config.slots)) {
    const vars = resolveSlotVars(name, slot, tokens)
    for (const [prop, val] of Object.entries(vars)) {
      out.push(`  ${prop}: ${val};`)
    }
  }
  out.push('}')
  out.push('')

  // Generic slot-inner base rule
  out.push('[data-slot] > .slot-inner {')
  out.push('  display: flex;')
  out.push('  flex-direction: column;')
  out.push('  width: 100%;')
  out.push('  flex: 1 0 auto;')
  out.push('}')
  out.push('')

  // Per-slot inner rules (consume vars, static across layouts).
  // Skip container slots — they hold a nested <div data-slot> instead of .slot-inner.
  for (const [name, slot] of Object.entries(config.slots)) {
    if (slot['nested-slots'] && slot['nested-slots'].length > 0) continue
    const pf = slotVarPrefix(name)
    out.push(`[data-slot="${name}"] > .slot-inner {`)
    out.push(`  max-width: var(${pf}-mw, none);`)
    out.push(`  padding: var(${pf}-pt, 0) var(${pf}-px, 0) var(${pf}-pb, 0);`)
    out.push(`  gap: var(${pf}-gap, 0);`)
    out.push(`  align-self: var(${pf}-al, stretch);`)
    out.push(`  margin-inline: auto;`)
    out.push('}')
    out.push('')
  }

  // ── Drawer base CSS ──
  // All drawer visuals (panel, backdrop, trigger, close) live in the portal
  // shell: packages/ui/src/portal/portal-shell.css. Layouts should never
  // emit drawer styling inline — one vocabulary across all layouts, all
  // themes, and the Layout Maker canvas preview.
  //
  // Per-layout knobs that the shell can't know in advance (drawer-width
  // per BP, which side is drawer-enabled) are still written as CSS var
  // overrides in the responsive @media blocks below.
  if (hasDrawers) {
    out.push('/* Drawer visuals: packages/ui/src/portal/portal-shell.css */')
    out.push('')
    // Silence "needLeftDrawer / needRightDrawer not used" — they are kept
    // computed so future per-layout overrides (e.g. per-side drawer-width
    // at a specific BP) can branch on them without re-walking the grid.
    void needLeftDrawer
    void needRightDrawer
  }

  // ── Responsive breakpoints ──
  for (let i = 1; i < bps.length; i++) {
    const [bpName, grid] = bps[i]
    const prevGrid = bps[i - 1][1]
    const maxWidth = parseInt(prevGrid['min-width'], 10) - 1

    out.push(
      `/* ── Grid: ${bpName} (${grid['min-width']} – ${maxWidth}px) ── */`,
    )
    out.push(`@media (max-width: ${maxWidth}px) {`)

    // Frame overrides
    const needsFrameReset = defaultGrid['max-width'] && !grid['max-width']
    const hasNewMaxWidth = !!grid['max-width']
    const centerChanged = defaultGrid.center && !grid.center

    if (needsFrameReset || hasNewMaxWidth || centerChanged) {
      out.push('  .layout-frame {')
      if (hasNewMaxWidth) {
        out.push(`    max-width: ${grid['max-width']};`)
      } else if (needsFrameReset) {
        out.push('    max-width: none;')
      }
      if (centerChanged) {
        out.push('    margin: 0;')
      } else if (grid.center) {
        out.push('    margin: 0 auto;')
      }
      out.push('  }')
      out.push('')
    }

    // Per-slot visibility: per-slot override wins, then grid-level sidebars fallback.
    // Computed BEFORE grid-template-columns so we can drop the tracks of hidden/drawered
    // slots — otherwise `display: none` on a child still leaves its 1fr track in the grid
    // and the remaining content shrinks to its original column width.
    //
    // Hidden vs drawered are handled differently downstream:
    //   - hidden:  `display: none` on the grid child (fully removed from render)
    //   - drawer:  position:fixed off-canvas panel that slides in via body
    //              class — the SAME DOM node that was a grid column, now a
    //              drawer panel. No duplicate content, so block JS that
    //              relies on a unique `document.querySelector` still hits.
    const hiddenSlots: string[] = []
    const drawerSlots: string[] = []
    const pushSlots: string[] = []
    for (const slotName of Object.keys(config.slots)) {
      const perSlotVis = grid.slots?.[slotName]?.visibility
      let effectiveVis: string | undefined
      if (perSlotVis) {
        effectiveVis = perSlotVis
      } else if (sidebarSlots.includes(slotName) && grid.sidebars) {
        effectiveVis = grid.sidebars
      }
      if (effectiveVis === 'hidden') hiddenSlots.push(slotName)
      else if (effectiveVis === 'drawer') drawerSlots.push(slotName)
      else if (effectiveVis === 'push') pushSlots.push(slotName)
    }
    // Both drawer and push take the slot out of the grid layout — grid
    // tracks collapse to content-only, sidebar is fixed-positioned.
    const hiddenSet = new Set([...hiddenSlots, ...drawerSlots, ...pushSlots])

    // Grid columns: skip nested children (rendered inside their parent) AND slots
    // that are hidden/drawered at this breakpoint (so the remaining columns
    // divide the full width).
    const cols = Object.entries(grid.columns)
      .filter(([name]) => !nestedChildren.has(name))
      .filter(([name]) => !hiddenSet.has(name))
      .map(([, w]) => w).join(' ')
    const gap = grid['column-gap']
      ? resolveValue(grid['column-gap'], tokens)
      : '0'

    out.push('  .layout-grid {')
    out.push(`    grid-template-columns: ${cols};`)
    if (gap !== '0') {
      out.push(`    column-gap: ${gap};`)
    } else {
      out.push('    column-gap: 0;')
    }
    out.push('  }')

    if (hiddenSlots.length > 0) {
      out.push('')
      const selectors = hiddenSlots.map((n) => `  .layout-grid > [data-slot="${n}"]`).join(',\n')
      out.push(`${selectors} {`)
      out.push('    display: none;')
      out.push('  }')
    }

    // Drawered sidebars — turn the in-grid <aside> into an off-canvas
    // drawer panel at this BP. Same DOM node that lived as a grid column
    // at desktop; CSS position:fixed pulls it out of grid flow. The
    // translate value reads from a shell-owned custom property that
    // portal-shell.js toggles via body class — no specificity race
    // between a closed-state rule and an open-state rule.
    for (const slotName of drawerSlots) {
      const side = slotName.includes('right') ? 'right' : 'left'
      const closed = side === 'left' ? '-100%' : '100%'
      out.push('')
      out.push(`  .layout-grid > [data-slot="${slotName}"] {`)
      out.push('    position: fixed;')
      out.push('    top: 0;')
      out.push('    bottom: 0;')
      out.push(`    ${side}: 0;`)
      out.push('    z-index: var(--drawer-z-panel);')
      out.push('    width: var(--drawer-panel-width);')
      out.push('    max-width: var(--drawer-panel-max-width);')
      out.push('    background: var(--drawer-panel-bg);')
      out.push(`    box-shadow: var(--drawer-panel-shadow-${side});`)
      out.push(`    transform: translateX(calc(var(--drawer-open-${side}, 1) * ${closed}));`)
      out.push('    transition: transform var(--drawer-enter-duration) var(--drawer-enter-easing);')
      out.push('    overflow-y: auto;')
      out.push('  }')
    }

    // Push-mode sidebars — sit flush at their edge with their own
    // background, layered BENEATH the content frame. When closed,
    // the layout-frame (z-index 2) covers them; when open, the
    // frame margin-slides off to reveal them. No shadow, no
    // backdrop — it's two layers sliding past each other.
    for (const slotName of pushSlots) {
      const side = slotName.includes('right') ? 'right' : 'left'
      out.push('')
      out.push(`  .layout-grid > [data-slot="${slotName}"] {`)
      out.push('    position: fixed;')
      out.push('    top: 0;')
      out.push('    bottom: 0;')
      out.push(`    ${side}: 0;`)
      out.push('    z-index: var(--drawer-z-push-sidebar);')
      out.push('    width: var(--drawer-panel-width);')
      out.push('    max-width: var(--drawer-panel-max-width);')
      out.push('    background: var(--drawer-panel-bg);')
      out.push('    overflow-y: auto;')
      out.push('  }')
    }

    // Per-slot CSS order for responsive stacking
    const orderRules: string[] = []
    for (const [slotName] of Object.entries(config.slots)) {
      const slotOrder = grid.slots?.[slotName]?.order
      if (slotOrder !== undefined) {
        orderRules.push(`  [data-slot="${slotName}"] { order: ${slotOrder}; }`)
      }
    }
    if (orderRules.length > 0) {
      out.push('')
      for (const r of orderRules) out.push(r)
    }

    // Drawer per-BP overrides. Trigger look + panel base styles come
    // from portal-shell.css; here we only:
    //   1. turn on .drawer-shell (default display:none in shell)
    //   2. pick the trigger variant at this BP by hiding the others.
    //      Markup carries every variant class the layout uses across
    //      all BPs (peek, hamburger, fab); the @media block we're in
    //      silences the ones NOT active here so only one variant's
    //      styles reach the button.
    //   3. write per-layout knobs (drawer-width).
    const hasDrawerAtBp =
      grid.sidebars === 'drawer' || grid.sidebars === 'push' ||
      Object.values(grid.slots ?? {}).some(
        (s) => s.visibility === 'drawer' || s.visibility === 'push',
      )

    if (hasDrawerAtBp) {
      out.push('')
      out.push('  .drawer-shell {')
      out.push('    display: contents;')
      out.push('  }')

      const variant = grid['drawer-trigger'] ?? 'peek'
      const allVariants: Array<'peek' | 'hamburger' | 'tab' | 'fab'> =
        ['peek', 'hamburger', 'tab', 'fab']
      for (const v of allVariants) {
        if (v === variant) continue
        out.push(`  .drawer-trigger.drawer-trigger--${v}:not(.drawer-trigger--${variant}) {`)
        out.push('    display: none;')
        out.push('  }')
      }

      if (grid['drawer-width']) {
        out.push('')
        out.push('  .drawer-panel {')
        out.push(`    width: ${grid['drawer-width']};`)
        out.push('  }')
      }
    }

    // Per-bp slot inner var overrides
    if (grid.slots) {
      const bpVars: string[] = []
      for (const [slotName, overrides] of Object.entries(grid.slots)) {
        const vars = resolveSlotVars(slotName, overrides, tokens)
        for (const [prop, val] of Object.entries(vars)) {
          bpVars.push(`    ${prop}: ${val};`)
        }
      }
      if (bpVars.length > 0) {
        out.push('')
        out.push('  :root {')
        for (const v of bpVars) out.push(v)
        out.push('  }')
      }

      // Per-bp border overrides
      for (const [slotName, overrides] of Object.entries(grid.slots)) {
        const hasBorderOverride = overrides['border-sides'] !== undefined ||
          overrides['border-width'] !== undefined || overrides['border-color'] !== undefined
        if (!hasBorderOverride) continue

        // Merge base + override to get effective config
        const baseSlot = config.slots[slotName] ?? {}
        const merged = { ...baseSlot, ...overrides }
        const sides = merged['border-sides']?.split(',') ?? []
        out.push('')
        out.push(`  [data-slot="${slotName}"] {`)
        out.push('    border: none;')
        if (sides.length > 0) {
          const bw = merged['border-width'] ?? '1px'
          const bc = resolveBackgroundCSS(merged['border-color'], tokens) ?? '#e2e8f0'
          for (const side of sides) {
            out.push(`    border-${side}: ${bw} solid ${bc};`)
          }
        }
        out.push('  }')
      }
    }

    out.push('}')
    out.push('')
  }

  return out.join('\n')
}
