import type { LayoutConfig } from './config-schema.js'

/** Get semantic HTML tag for a slot name */
function getTag(name: string): string {
  if (name === 'content') return 'main'
  if (name.includes('sidebar')) return 'aside'
  return 'div'
}

/** Inner HTML for a slot: nested-child placeholders (no whitespace) or empty. */
function renderSlotInner(slot: { 'nested-slots'?: string[] }): string {
  const nested = slot['nested-slots']
  if (nested && nested.length > 0) {
    return nested.map((child) => `<div data-slot="${child}"></div>`).join('')
  }
  return ''
}

// eslint-disable-next-line sonarjs/cognitive-complexity
export function generateHTML(config: LayoutConfig): string {
  const out: string[] = []
  const slots = config.slots

  // Determine drawer configuration
  const hasDrawers = Object.values(config.grid).some(
    (g) => g.sidebars === 'drawer',
  )

  let needLeftDrawer = false
  let needRightDrawer = false
  const sidebarSlots: string[] = []

  if (hasDrawers) {
    for (const g of Object.values(config.grid)) {
      if (g.sidebars === 'drawer') {
        const pos = g['drawer-position'] ?? 'both'
        if (pos === 'left' || pos === 'both') needLeftDrawer = true
        if (pos === 'right' || pos === 'both') needRightDrawer = true
      }
    }
    for (const name of Object.keys(slots)) {
      if (name.includes('sidebar')) sidebarSlots.push(name)
    }
  }

  // Categorize slots by position
  const topSlots = Object.entries(slots).filter(
    ([, s]) => s.position === 'top',
  )
  const bottomSlots = Object.entries(slots).filter(
    ([, s]) => s.position === 'bottom',
  )

  // Desktop column order (highest min-width breakpoint)
  const desktopBp = Object.entries(config.grid).sort(
    (a, b) =>
      parseInt(b[1]['min-width'], 10) - parseInt(a[1]['min-width'], 10),
  )[0]
  const desktopColumns = Object.keys(desktopBp[1].columns)

  // Comment header
  out.push(`<!-- Layout: ${config.name} | Scope: ${config.scope} -->`)
  out.push('<!-- Generated by Layout Maker — do not edit manually -->')
  out.push('')

  // Top-position slots (header, hero, etc.)
  for (const [name, slot] of topSlots) {
    const tag = getTag(name)
    const inner = renderSlotInner(slot)
    out.push(`<${tag} data-slot="${name}">${inner}</${tag}>`)
    out.push('')
  }

  // Collect nested children — these render inside their parent, not as grid columns
  const nestedChildren = new Set<string>()
  for (const s of Object.values(slots)) {
    const nl = s['nested-slots']
    if (Array.isArray(nl)) nl.forEach((c) => nestedChildren.add(c))
  }

  // Grid frame
  out.push('<div class="layout-frame">')
  out.push('  <div class="layout-grid">')

  for (const name of desktopColumns) {
    if (nestedChildren.has(name)) continue
    const tag = getTag(name)
    const slot = slots[name] ?? {}
    const inner = renderSlotInner(slot)
    out.push(`    <${tag} data-slot="${name}">${inner}</${tag}>`)
  }

  out.push('  </div>')
  out.push('</div>')
  out.push('')

  // Bottom-position slots (footer, etc.)
  for (const [name, slot] of bottomSlots) {
    const tag = getTag(name)
    const inner = renderSlotInner(slot)
    out.push(`<${tag} data-slot="${name}">${inner}</${tag}>`)
    out.push('')
  }

  // Drawer elements (only if any breakpoint uses drawers)
  if (hasDrawers) {
    out.push('<!-- Drawers (tablet/mobile) -->')
    out.push(
      '<div class="layout-drawer-backdrop" id="drawerBackdrop"></div>',
    )
    out.push('')

    if (needLeftDrawer) {
      const leftSidebar =
        sidebarSlots.find((n) => n.includes('left')) ?? sidebarSlots[0]
      if (leftSidebar) {
        out.push(
          '<div class="layout-drawer layout-drawer--left" id="drawerLeft">',
        )
        out.push(
          '  <button class="drawer-close" aria-label="Close sidebar">&times;</button>',
        )
        out.push(`  <div data-slot="${leftSidebar}"></div>`)
        out.push('</div>')
        out.push('')
      }
    }

    if (needRightDrawer) {
      const rightSidebar =
        sidebarSlots.find((n) => n.includes('right')) ??
        sidebarSlots.at(-1)
      if (rightSidebar) {
        out.push(
          '<div class="layout-drawer layout-drawer--right" id="drawerRight">',
        )
        out.push(
          '  <button class="drawer-close" aria-label="Close sidebar">&times;</button>',
        )
        out.push(`  <div data-slot="${rightSidebar}"></div>`)
        out.push('</div>')
        out.push('')
      }
    }

    // Trigger buttons
    if (needLeftDrawer) {
      out.push(
        '<button class="drawer-trigger drawer-trigger--left" aria-label="Open left sidebar">',
      )
      out.push('  <span class="drawer-trigger__icon">&#9776;</span>')
      out.push('</button>')
      out.push('')
    }

    if (needRightDrawer) {
      out.push(
        '<button class="drawer-trigger drawer-trigger--right" aria-label="Open right sidebar">',
      )
      out.push('  <span class="drawer-trigger__icon">&#9881;</span>')
      out.push('</button>')
      out.push('')
    }

    // Inline script — self-contained IIFE, no dependencies
    out.push('<script>')
    out.push('  (function() {')
    out.push("    const backdrop = document.getElementById('drawerBackdrop');")
    out.push(
      "    const triggers = document.querySelectorAll('.drawer-trigger');",
    )
    out.push(
      "    const drawers = document.querySelectorAll('.layout-drawer');",
    )
    out.push("    const closes = document.querySelectorAll('.drawer-close');")
    out.push('')
    out.push('    function openDrawer(id) {')
    out.push("      document.getElementById(id)?.classList.add('open');")
    out.push("      backdrop?.classList.add('open');")
    out.push('    }')
    out.push('')
    out.push('    function closeAll() {')
    out.push("      drawers.forEach(d => d.classList.remove('open'));")
    out.push("      backdrop?.classList.remove('open');")
    out.push('    }')
    out.push('')
    out.push('    triggers.forEach(t => {')
    out.push("      t.addEventListener('click', () => {")
    out.push(
      "        const side = t.classList.contains('drawer-trigger--left') ? 'drawerLeft' : 'drawerRight';",
    )
    out.push('        openDrawer(side);')
    out.push('      });')
    out.push('    });')
    out.push('')
    out.push(
      "    closes.forEach(c => c.addEventListener('click', closeAll));",
    )
    out.push("    backdrop?.addEventListener('click', closeAll);")
    out.push('  })();')
    out.push('</script>')
  }

  return out.join('\n')
}
